-- Add payment fields to persone table
ALTER TABLE persone ADD COLUMN IF NOT EXISTS totale_da_pagare DOUBLE PRECISION;
ALTER TABLE persone ADD COLUMN IF NOT EXISTS rata_iscrizione DOUBLE PRECISION;
ALTER TABLE persone ADD COLUMN IF NOT EXISTS rata1 DOUBLE PRECISION;
ALTER TABLE persone ADD COLUMN IF NOT EXISTS rata2 DOUBLE PRECISION;
ALTER TABLE persone ADD COLUMN IF NOT EXISTS rata3 DOUBLE PRECISION;
ALTER TABLE persone ADD COLUMN IF NOT EXISTS rata4 DOUBLE PRECISION;
ALTER TABLE persone ADD COLUMN IF NOT EXISTS rata_saldo DOUBLE PRECISION;

-- Add missing persona fields
ALTER TABLE persone ADD COLUMN IF NOT EXISTS residenza VARCHAR(100);
ALTER TABLE persone ADD COLUMN IF NOT EXISTS indirizzo VARCHAR(200);
ALTER TABLE persone ADD COLUMN IF NOT EXISTS cittadinanza VARCHAR(50);
ALTER TABLE persone ADD COLUMN IF NOT EXISTS tel_papa VARCHAR(20);
ALTER TABLE persone ADD COLUMN IF NOT EXISTS tel_mamma VARCHAR(20);
ALTER TABLE persone ADD COLUMN IF NOT EXISTS email1 VARCHAR(100);
ALTER TABLE persone ADD COLUMN IF NOT EXISTS email2 VARCHAR(100);
ALTER TABLE persone ADD COLUMN IF NOT EXISTS prof_papa VARCHAR(100);
ALTER TABLE persone ADD COLUMN IF NOT EXISTS prof_mamma VARCHAR(100);
ALTER TABLE persone ADD COLUMN IF NOT EXISTS anamnesi TEXT;
ALTER TABLE persone ADD COLUMN IF NOT EXISTS taglia VARCHAR(10);
ALTER TABLE persone ADD COLUMN IF NOT EXISTS nome_papa VARCHAR(100);
ALTER TABLE persone ADD COLUMN IF NOT EXISTS nome_mamma VARCHAR(100);
ALTER TABLE persone ADD COLUMN IF NOT EXISTS comune_nato VARCHAR(100);
ALTER TABLE persone ADD COLUMN IF NOT EXISTS note TEXT;
