from .anagrafica import PersonaCreate, PersonaOut, PersonaCertificatoUpdate
from .presenze import CodiceOut, RegistroEntry, RegistroOut
from .partite import (
    PartitaCreate,
    PartitaUpdate,
    WeekendCreate,
    WeekendUpdate,
    SpogliatoioCreate,
    SpogliatoioUpdate,
    SpogliatoioAssegnazioneCreate,
    SpogliatoioAssegnazioneUpdate,
    SpogliatoioAssegnazioneSettimanaSave,
    SpogliatoioAssegnazioneWeekendSave,
    CampoCreate,
    CampoUpdate,
    CampoAssegnazioneCreate,
    CampoAssegnazioneUpdate,
    CampoAssegnazioneSettimanaSave,
    CampoAssegnazioneWeekendSave,
)
from .segreteria import OpendayCreate, OpendayUpdate

__all__ = [
    "PersonaCreate",
    "PersonaOut",
    "PersonaCertificatoUpdate",
    "CodiceOut",
    "RegistroEntry",
    "RegistroOut",
    "PartitaCreate",
    "PartitaUpdate",
    "WeekendCreate",
    "WeekendUpdate",
    "SpogliatoioCreate",
    "SpogliatoioUpdate",
    "SpogliatoioAssegnazioneCreate",
    "SpogliatoioAssegnazioneUpdate",
    "SpogliatoioAssegnazioneSettimanaSave",
    "SpogliatoioAssegnazioneWeekendSave",
    "CampoCreate",
    "CampoUpdate",
    "CampoAssegnazioneCreate",
    "CampoAssegnazioneUpdate",
    "CampoAssegnazioneSettimanaSave",
    "CampoAssegnazioneWeekendSave",
    "OpendayCreate",
    "OpendayUpdate",
]
